### ISSUE TITLE
Dark mode background in built-in Canvas file viewer

### ISSUE THREAD

**Issue by ds196** [ksucpea/bettercanvas#74]
Hello,

I have written a tiny bit of CSS to make the background of the file viewer in Canvas dark mode so it is less jarring compared to the rest of the screen. I have found that, even though documents almost always have a white background, the file viewer background being dark makes it a lot easier on the eyes.

Before:
![image](https://github.com/user-attachments/assets/523bfb58-f7bf-47ac-90ba-a25bf540e249)

After:
![image](https://github.com/user-attachments/assets/02fc212d-d276-496a-8bf7-33d0f1b971a0)

Here is the code that should be applied to `canvadocs.instructure.com/*`:
```css
div#App nav.ViewerControls,
div#app div.Pages {
    scrollbar-color: #999 #414a55;
}

div#App div.Pages {
    background: #313941;
}
```
I apologize that this is not in the form of a pull request, as I do not know how to add CSS to your source code. I hope this makes your dark mode just a little bit better.

Best,
David
