### ISSUE TITLE
Assignments header is not dark mode

### ISSUE THREAD

**Issue by ds196** [ksucpea/bettercanvas#75]
It seems like assignment details pages have been updated in some way, and now the top of the page is not dark mode.

Example:
![image](https://github.com/user-attachments/assets/1e7cacf3-3c54-4b90-8a24-228f235e5f99)

The dark mode inspector fixes most of it, but not the background:
![image](https://github.com/user-attachments/assets/7b71c3b2-e793-4d00-bcb2-897df7ec94ce)

Output of the dark mode inspector: [https://pastebin.com/DeFuv8rE](https://pastebin.com/DeFuv8rE)

The closest reliable selector seems to be `div#content.ic-Layout-contentMain`:
![image](https://github.com/user-attachments/assets/1b2115a5-2e94-4b3b-91e2-c71dc11d9a73)

Best,
David

**Comment by ds196** [comment]
Fixed
```css
/* Header */
div[data-testid="assignments-2-student-view"]>div[class$="-view"] {
    background-color: #161616;
}

/* Header text */
div[data-testid="assignments-2-student-view"] span[class$="-text"] {
    color: #aaa;
}
```
![image](https://github.com/user-attachments/assets/7438a832-1b7c-4a4d-9c67-49d565168df3)
