### ISSUE TITLE
A gap at the top and bottom of the side bar logo

### ISSUE THREAD

**Issue by AdoreJc** [ksucpea/bettercanvas#86]
When dark mod is on it removes the background-color of the logo.
I hope this rule can be excluded.
```css
.ic-app-header__logomark-container {
    background: none !important;
}
```
Or the gap can be removed.
```css
.ic-app-header__logomark {
    display: block;
    overflow: hidden;
    background-image: var(--ic-brand-header-image);
    background-position: 50%;
    background-repeat: no-repeat;
    background-size: contain;
    transition: transform .3s;
    height: 75px;
}
```
Remove `height` and add `padding-top: 100%; ` will remove the gap.

**Comment by ksucpea** [comment]
Could you send a screenshot of this?

**Comment by AdoreJc** [comment]
It originally is looked like this.
![image](https://github.com/user-attachments/assets/00cd7dc7-1bee-4d05-945a-b39e3043a8cc)
```html
<div class="ic-app-header__logomark-container">
    <a href="https://uwosh.instructure.com/" class="ic-app-header__logomark">
        <span class="screenreader-only">Dashboard</span>
    </a>
</div>
```
```css
.ic-app-header__logomark-container {
    width: 100%;
    background-color: var(--ic-brand-global-nav-logo-bgd);
    box-sizing: border-box;
}
```
When dark mode is on, it removes the logo's background-color, making it look a little bit off.
![image](https://github.com/user-attachments/assets/3d5dc393-6a00-4e53-a3b6-f5c0d3177cc1)
```css
.ic-app-header__logomark-container {
    background: none !important;
}
```
Remove `height` and add `padding-top` can remove the gaps in between.
```css
.ic-app-header__logomark {
    display: block;
    overflow: hidden;
    background-image: var(--ic-brand-header-image);
    background-position: 50%;
    background-repeat: no-repeat;
    background-size: contain;
    transition: transform .3s;
    /* height: 75px; */
    padding-top: 100%; /* add this */
}
```
![image](https://github.com/user-attachments/assets/4a20bf30-c5e9-4273-8f0b-d802b14b1f91)
